### ISSUE TITLE
Doesn't show "tabs from other devices"

### ISSUE THREAD

**Issue by BlueDrink9** [dragonofmercy/Chrome-Better-History#12]
Unlike stock chrome history, this extension doesn't allow showing tabs from other devices, for handoffs.

The easiest way around this would just be to have a link to chrome://history/syncedTabs

**Comment by dragonofmercy** [comment]
This functionality is not available trough chrome api

**Comment by BlueDrink9** [comment]
As stated, you don't need any api function. All you need to do is add a link to the above url `chrome://history/syncedTabs`

**Comment by dragonofmercy** [comment]
I've try this method, it's not working, my link is automatically disabled

**Comment by BlueDrink9** [comment]
Oh, true. My mistake. Alas
