### ISSUE TITLE
Dark Theme?

### ISSUE THREAD

**Issue by ghost** [dragonofmercy/Chrome-Better-History#13]
A dark theme would be great

**Comment by dragonofmercy** [comment]
Hi I will create a dark theme when the css "prefers-color-scheme" will be available on chrome

**Comment by Aidolii** [comment]
Seems like that's available now, assuming that hooks into whether you're using the light or dark theme in Windows.

**Comment by dragonofmercy** [comment]
Finally I've included the dark theme, will be available on next update, sorry for delay
