### ISSUE TITLE
Missing records that exist on Chrome's native history

### ISSUE THREAD

**Issue by MeiRct** [dragonofmercy/Chrome-Better-History#14]
I found out 3 records that are missing from the addon history display, but are listed in the regular Chrome history.
In this specific case, those happened to be the only records for that day, and 3 of them are pages of Google apps - 1 Gmail page and 2 Google Sheets pages.

Screenshot from Chrome's native history:
![image](https://user-images.githubusercontent.com/11060682/55476955-94637900-5620-11e9-9ed8-b66ce75d85f2.png)
(The title is "Monday, April 1st 2019" in Hebrew language interface)

Screenshot from Chrome Better History addon:
![image](https://user-images.githubusercontent.com/11060682/55476700-f4a5eb00-561f-11e9-90db-2d013401efd0.png)

There was no any crash or unexpected behavior of the browser or the computer that day.

I will happy to assist and debug following some instructions, if needed.

**Comment by dragonofmercy** [comment]
Hi, It's very strange, the problem is that I use `chrome.history.search` function, if this function doesn't return items it's a chrome bug...

**Comment by MeiRct** [comment]
@dragonofmercy I debugged the script execution, and actually it does retrieve the 3 results correctly by the ```chrome.history.search``` API call, as can be seen in the Scope > Local section in the developer tools:
![image](https://user-images.githubusercontent.com/11060682/55479879-b3b1d480-5627-11e9-90b3-216b5ec6dcfb.png)

But then probably fails to display them, due to favicon permission error:
![image](https://user-images.githubusercontent.com/11060682/55479979-f1166200-5627-11e9-8e1b-17b1ad39c6a3.png)

Similar errors are logged also in console, but not necessarily right after the ```historyResponse``` call:
![image](https://user-images.githubusercontent.com/11060682/55480123-3d61a200-5628-11e9-9980-414900661ddb.png)

The extention does have [permissions to ```chrome://favicon```](https://github.com/dragonofmercy/Chrome-Better-History/blob/master/manifest.json#L12), and succeeds to display all the rest of favicons (including Gmail and Google Sheets), so I don't know what can be the cause, and I had a bit of hard time to debug deeper.
Please don't hesitate to instruct me where to look further if you need.

I guess that some error handler and fallback for the styling (maybe some default banal favicon like 📄) might be added [inside ```getFavicon``` function object](https://github.com/dragonofmercy/Chrome-Better-History/blob/master/assets/scripts.js#L89).

Hope that I provided correct and useful information.

**Comment by dragonofmercy** [comment]
Ok I will check that

**Comment by dragonofmercy** [comment]
Ok I have published a new version to remove favicon error, can you try with the 3.10 ?

**Comment by MeiRct** [comment]
Thank you for you efforts.

Unfortunately, the issue was still there also after the update, so I inspected once again, this time deeper, and probably found out the real cause.
As we know, the query to ```chrome.history.search``` was for Apr 01, 2019. 
However, have a look at ```item_date``` object in the left "Scope" panel, which was created from the ```result.lastVisitTime```:
![image](https://user-images.githubusercontent.com/11060682/55554145-bde8d700-56ea-11e9-9516-8e3d204727d8.png)
We would expect it to be Apr 01, 2019, while actually it's Apr **03**, 2019, which is apparently the real last date (as in **last**VisitTime) of visiting this URL afterwards, regardless of the actual visit datetime of the returned history record.

I googled and found that this behavior was mentioned in the following feature request on Chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=148928
It even also mentions the old "Better History" extension which was affected from this too.
Unfortunately the issue was archived due to inactivity, and obviously it should be reopened.

From this finding we can understand that this behavior **happens in the extension with a lot of other history records** - all those that their URL was visited again afterwards. They will show up only in the latest day they were visited, and will be missing from all of their previous expected occurrences in the **whole** history.
I believe you can reproduce it easily by searching for some page that were visited with the exact same URL in other days.

Luckily, it was noticeable to me thanks to the fact that those 3 records were the only ones of Apr 01, and all of the 3 URLs were opened in the browser also afterwards. 
This led to the Apr 01 day display being completely empty in the "Chrome Better History" interface, while I was certain that I used the browser on that day for that specific Chrome profile , and I needed the history records for making some activity report.
Otherwise, if there would have been more history records on that day (which weren't visited again afterwards), there's a chance we would never notice that.

Please tell me if you think of any way to tackle this issue (maybe by switching to the [```chrome.history.getVisits``` method of the history API](https://developer.chrome.com/extensions/history#method-getVisits)?), or if you intend to reopen the issue on Chromium website.

**Comment by NZnick** [comment]
I can confirm that I am experiencing the same issue and that it appears to be that each unique URL is only recorded in the history once with at the date it was last accessed. Clicking on a link previously accessed removes it from that days history record but places it in the current days history record.

**Comment by jiacai2050** [comment]
Hi, I'm the author of [history master](https://github.com/jiacai2050/history-master), this issue is very annoying if users want to display histories day by day. 
Maybe we can vote [bug-148928](https://bugs.chromium.org/p/chromium/issues/detail?id=148928) to reopen it.
