### ISSUE TITLE
Unable to Clear History?

### ISSUE THREAD

**Issue by Jack0Knife** [dragonofmercy/Chrome-Better-History#16]
Hello,

I read that the #11 issue, "clear all" button was removed, but perhaps a deleting specific site visits or deleting sites from a specific time frame would be a perfect middle ground?

Also, why not have a confirmation dialogue to mitigate this issue? Removing the functionality to delete history seems like a bizarre solution to the problem.

**Comment by dragonofmercy** [comment]
A confirmation box was implemented with this option when it was implemented, a lot of stupid users don't care and send me e-mail and support about that. So use the chrome internal remove history: chrome://settings/clearBrowserData
