### ISSUE TITLE
How about Ctrl+z to open the latest closed page？

### ISSUE THREAD

**Issue by zhz1237ok** [dragonofmercy/Chrome-Better-History#17]
it would be better to quickly reopen the latest closed page and this function is used by many history-like plguins

**Comment by dragonofmercy** [comment]
Sorry but a can't do that because a need more permissions which has no relation with history.
You can use other extensions like mouse gestures to do that. I recommend this one: https://chrome.google.com/webstore/detail/smartup-gestures/bgjfekefhjemchdeigphccilhncnjldn
