### ISSUE TITLE
expand the history record？

### ISSUE THREAD

**Issue by lnxzy2** [dragonofmercy/Chrome-Better-History#18]
Now the history is limited as 90 days, could you please add a option to expand the history to all days?

**Comment by dragonofmercy** [comment]
Hi, it's not possible now with the chrome.history.api. I know that some extension save more than 90 day but they put all your history data in cloud, I don't want to do that to keep my extension privacy secure.

A support is open from 2015 on the chromium project https://bugs.chromium.org/p/chromium/issues/detail?id=500239.
