### ISSUE TITLE
there is a typesetting disorder

### ISSUE THREAD

**Issue by Jackxwb** [dragonofmercy/Chrome-Better-History#21]
It's been used a long time ago, but recently when I wanted to use it again, I found that there was confusion in typesetting.
My browser version:
navigator.userAgent="Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
![X CW$}AR`3 7L)4N3S193Z5](https://user-images.githubusercontent.com/34720403/63738279-d9cc5f80-c8bb-11e9-80bc-1d1793e5869c.png)
![2@Y{8PHR7G`ON0C5 O08IMU](https://user-images.githubusercontent.com/34720403/63738280-da64f600-c8bb-11e9-8479-240ab2cdc1d0.png)

-- The above text comes from Baidu Translation Engine --

**Comment by Jackxwb** [comment]
This is the “chrome://history/” tab page now.
![X CW$}AR`3 7L)4N3S193Z5](https://user-images.githubusercontent.com/34720403/63738607-d5547680-c8bc-11e9-8c6a-88d8483ad3a8.png)

**Comment by dragonofmercy** [comment]
You are using CentBrowser, I think that's the problem, my extension is only tested with Google Chrome and Microsoft Edge Chromium Beta.
As I see on the screenshot the internal CSS are not the same than in Chrome, that's why you have an ugly interface with my extension.

**Comment by Jackxwb** [comment]
I know what happened.
I installed another plug-in, which produces a special URL record (which contains the main body of html) and then loads the CSS style in the parser when the plug-in reads the history, which will disrupt the CSS style of the current page.
![image](https://user-images.githubusercontent.com/34720403/65308556-e42d0100-dbbc-11e9-9818-88f33cf1673c.png)
this html url:
`data:text/html,<!DOCTYPE html><html>  <head>    <title>Sticky Window - Distill</title>    <meta charset='utf-8'>    <style>.hide { display: none !important; }    body {      width: 600px;      margin: auto;      margin-top: 50px;      font-size: x-large;    }     </style>  </head>  <body style="">    <div style="margin-bottom: 20px;" class="alert alert-info" role="alert">      HEADS UP! Distill uses a placeholder tab to mark this Sticky Window. This helps us check whether session needs to be restored on startup. To change this behavior please go to the "Settings > Advanced" page in your extension.    </div>    <div class="alert alert-danger" style="background-color: #ce2759; color: #fff; padding: 10px; border-radius: 5px;" role="alert">      WARNING! Closing this tab will result in loss of session data, and you will have to manually restore your session.    </div>  </body></html>`
![image](https://user-images.githubusercontent.com/34720403/65308676-27876f80-dbbd-11e9-99fb-972e736efda2.png)
After deleting the record
![image](https://user-images.githubusercontent.com/34720403/65309321-7386e400-dbbe-11e9-95da-51b0a2d90784.png)

**Comment by dragonofmercy** [comment]
Ok I find the problem, it will be fix with the version 3.22
