### ISSUE TITLE
Add Simplified Chinese translation

### ISSUE THREAD

**Issue by Vstory** [dragonofmercy/Chrome-Better-History#24]
Is it possible to support displaying the date and time of localization in accordance with the browser language settings?

**Comment by dragonofmercy** [comment]
Can you give me an example because it's already made
RU: d mmmm yyyy, dddd
FR: dddd, d mmmm yyyy
EN:  dddd, mmmm d, yyyy
DE: dddd, d. mmmm yyyy

**Comment by Vstory** [comment]
> Can you give me an example because it's already made


I mean the year, month and day show the local language instead of English.The language of the year, month, and day is displayed, following the browser language.

**Comment by dragonofmercy** [comment]
This is already done, below you can see an example in french
![2019-09-30_14-05-00](https://user-images.githubusercontent.com/140013/65877247-6ff81780-e38b-11e9-9f32-e03f68a2ea8c.jpg)
All are translated! Only RU, FR, EN and DE are available right now.
What language do you want ?

**Comment by Vstory** [comment]
> This is already done, below you can see an example in french
> ![2019-09-30_14-05-00](https://user-images.githubusercontent.com/140013/65877247-6ff81780-e38b-11e9-9f32-e03f68a2ea8c.jpg)
> All are translated! Only RU, FR, EN and DE are available right now.
> What language do you want ?


I want you to support Chinese.Although English does not affect reading, it is still better for the native language.

**Comment by dragonofmercy** [comment]
For this you have to make me a pull request with the new language, because I don't speak chinese.
Have a look in the previous pull request to see how to do it.
https://github.com/dragonofmercy/Chrome-Better-History/pulls?q=is%3Apr+is%3Aclosed
