### ISSUE TITLE
add categories/hashtags

### ISSUE THREAD

**Issue by miguel-ka** [dragonofmercy/Chrome-Better-History#31]
Hi dragonofmercy,
another wish for a break through feature would be possibility to add simple categories (like hashtags) and possibly remarks to it.

e.g.
![image](https://user-images.githubusercontent.com/33891992/71831583-7b08c500-30a9-11ea-9f57-c576731ecf0b.png)

Thanks in advance!
miguel-ka

**Comment by dragonofmercy** [comment]
Hi thanks for your proposition but this extension will only based on the chrome api capacity, for adding tags a need to create a local database to store your informations, that's not the philosophy of this extension.
