### ISSUE TITLE
Incorrect date display sometimes

### ISSUE THREAD

**Issue by maxvlas** [dragonofmercy/Chrome-Better-History#33]
**Hello.**
there is no word and shows this
February 1, 1970
![2020-01-23_195434](https://user-images.githubusercontent.com/11572859/73006389-a1559100-3e1b-11ea-91a1-b9d24ab78e7e.png)
In a normal story, everything is fine.
![2020-01-23_200720](https://user-images.githubusercontent.com/11572859/73006792-47090000-3e1c-11ea-9f67-1ff45202e4eb.png)

**Google Chrome Version 79.0.3945.130 (Official Build), (32 bit)**

**Comment by dragonofmercy** [comment]
This will be fixed in the next big update

**Comment by maxvlas** [comment]
> This will be fixed in the next big update

Good.
Thanks for the support.
