### ISSUE TITLE
Links disappear from history.

### ISSUE THREAD

**Issue by maxvlas** [dragonofmercy/Chrome-Better-History#36]
Links disappear from history after clicking on them.
Today is March 12th.
I followed the link from March 11 (on the photo 5 point)
![2020-03-12_084552](https://user-images.githubusercontent.com/11572859/76491778-90022b80-643f-11ea-9552-f4506cc6a223.png)
Now again, we look at the story of March 11th.
We see that there is no longer this link in history.
Point 5 is gone.
It turns out that on March 11 I was not there by reference.
![2020-03-12_084818](https://user-images.githubusercontent.com/11572859/76492064-51b93c00-6440-11ea-8aa1-83314084776c.png)
We will register this link in the search and see that I was only on March 12
![2020-03-12_090233](https://user-images.githubusercontent.com/11572859/76492102-72819180-6440-11ea-9b5e-cbebd2c654ea.png)
In ordinary history, for some reason, too, it shows.
![2020-03-12_090712](https://user-images.githubusercontent.com/11572859/76492333-fcc9f580-6440-11ea-888a-aae90ba1d6b9.png)

**Comment by dragonofmercy** [comment]
It's normal, this is how Chrome history works, it keep only the last visit
see #14

**Comment by maxvlas** [comment]
> It's normal
Now everything is clear.
Thanks for the support and convenient extension.
