### ISSUE TITLE
date after search

### ISSUE THREAD

**Issue by maxvlas** [dragonofmercy/Chrome-Better-History#37]
Today is March 19th.
I open the story on March 18th.
I register in the search, then close the search, write in the main window on March 19, and on the left on the calendar we see the remaining on March 18.
![1Q04AFhulM](https://user-images.githubusercontent.com/11572859/77036177-863c7300-69bf-11ea-9f9a-58ac335aaf7a.gif)

**Comment by dragonofmercy** [comment]
Hi, the search doesn't take care about the current date, it search all over the history.
I have no plans right now to add search by date, a new version will coming in few weeks with many interface improvement.

**Comment by maxvlas** [comment]
It is clear that throughout history is looking.
You just didn’t understand me.
See:
For example, I look at the history of March 18 (on the left it shows on the
calendar on March 18 and in the main window on March 18)
I registered a word in the search, then clicked the cross, cleared the search
history.
In the main window, we have March 20, then the calendar on the left should
probably also be March 20, if everything returns to its original position

  19.03.2020, 09:55, Dragon <notifications@github.com>


  Hi, the search doesn't take care about the current date, it search all over
  the history.
  I have no plans right now to add search by date, a new version will coming in
  few weeks with many interface improvement.
