### ISSUE TITLE
When accessing a URL which has been visited before, the previous histrory of this URL is deleted. 

### ISSUE THREAD

**Issue by gdfeihu** [dragonofmercy/Chrome-Better-History#39]
When accessing a URL which has been visited before, the previous histrory of this URL is deleted. It seems that only one record for a specified URL can be saved, that is to say if one visit a URL for several times, only the latest record can be saved in the history, all the previous access record will be lost.

**Comment by dragonofmercy** [comment]
Duplicate with #14
