### ISSUE TITLE
Filter options or grouping entries by device

### ISSUE THREAD

**Issue by michagrandel** [dragonofmercy/Chrome-Better-History#5]
If I use the original history of chrome (at least in the menu, see the screenshot for example), the history is grouped by devices.

![chromehistory](https://user-images.githubusercontent.com/2573821/47288778-d317f080-d5f7-11e8-9f9a-489120b3daa3.png)

I suggest a filter option (e.g. checkboxes), where you can select the devices you want to display and/or some ui to group the history entries.

**Comment by dragonofmercy** [comment]
Hi,
I use the hrome.history.search api to get the history items, the problem is that api doesn't allow to get the history items from other devices.

**Comment by cryptid11** [comment]
then you should look in the code for the http request, I mean the thing isn't magic, even if Google ppl are apparently quite unable to make apis is still solvable
